name = "1000h-entry"
main = "index.js"
workers_dev = false
compatibility_date = "2023-03-23"

routes = ["1000h.org/*"]
services = [
  { binding = "vtp", service = "1000h-vtp" },
  { binding = "portal", service = "1000h-portal" },
]

[vars]
HOST = "https://1000h.org"

